FROM node AS build

COPY . /workspace
WORKDIR /workspace
RUN cd time-tracker-frontend && npm install && npm run-script build

FROM nginx:latest
COPY --from=build /workspace/time-tracker-frontend/build/ /var/www
COPY nginx.conf /etc/nginx/nginx.conf

EXPOSE 80

CMD ["nginx"]
