FROM golang:1.13-alpine as build
RUN apk update && apk add --no-cache git make
COPY . /workspace
WORKDIR /workspace
ARG _TAG
ENV VERSION ${_TAG}
RUN make -C ./time-tracker build

FROM alpine:latest
RUN apk update && apk add --no-cache tzdata
COPY --from=build /workspace/time-tracker/bin/time-tracker /bin/time-tracker
EXPOSE 8080
