version: '3'

services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: 'postgres' # don't do this! store the password in a secret instead
    # ports:
    #   - "5432:5432"
    expose:
      - "5432"
    volumes:
      - ./initdb:/docker-entrypoint-initdb.d

  time-tracker:
    build:
      context: .
      dockerfile: Dockerfile.tt
    environment:
      HTTP_ADDR: ":8080"
      TIME_REC_DB_DSN: "postgres://postgres:postgres@db:5432/postgres?sslmode=disable" # store this in a secret and enable SSL
    depends_on:
      - db
    expose:
      - "8080"
    restart: on-failure
    command: /bin/time-tracker

  gateway:
    build:
      context: .
      dockerfile: Dockerfile.ga
    depends_on:
      - time-tracker
    environment:
      HTTP_ADDR: ":8080"
      METRICS_ADDR: ":9102"
    ports:
      - "8080:8080"
    expose:
      - "9102"
    restart: on-failure
    command: /bin/gateway --cfg-file=/config/config.yaml

