version: '3'

services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: 'postgres' # don't do this! store the password in a secret instead
    expose:
      - "5432"
    volumes:
      - ./initdb:/docker-entrypoint-initdb.d
    networks:
      - app-network

  time-tracker:
    build:
      context: .
      dockerfile: Dockerfile.tt
    environment:
      HTTP_ADDR: ":8081"
      TIME_REC_DB_DSN: "postgres://postgres:postgres@db:5432/postgres?sslmode=disable" # store this in a secret and enable SSL
    depends_on:
      - db
    expose:
      - "8081"
    restart: on-failure
    command: /bin/time-tracker
    networks:
      - app-network

  webserver:
    build:
      context: .
      dockerfile: Dockerfile.ng
    container_name: webserver
    restart: on-failure
    tty: true
    depends_on:
      - time-tracker
    ports:
      - "80:80"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
